# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.


# Site Settings
locale                   : "en-US"
title                    : Logan Abramowitz
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : Logan Abramowitz
description              : Logan Abramowitz - Projects and CV 
baseurl                  : "" # Set this to "portfolio-<your-github-username>" 
url                      : "https://Logan-Abramowitz.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"

# Theme and Style
theme: jekyll-theme-minimal
color_scheme: dark # light/default, dark, or aqua
skin: aqua

sass:
  style: compressed

# Outputting
permalink: /:categories/:title/

collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /:collection/:path/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

